### ISSUE TITLE
monetdb python API can handle only unicode or utf-8 encoded strings

### ISSUE THREAD

**Issue by gijzelaerr** [gijzelaerr/sqlalchemy-monetdb#2]
```
======================================================================
ERROR: test_suite.UnicodeTextTest.test_literal
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/SQLAlchemy-0.9.4-py2.7-macosx-10.9-x86_64.egg/sqlalchemy/testing/suite/test_types.py", line 123, in test_literal
    self._literal_round_trip(self.datatype, [self.data], [self.data])
  File "<string>", line 2, in _literal_round_trip
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/SQLAlchemy-0.9.4-py2.7-macosx-10.9-x86_64.egg/sqlalchemy/testing/util.py", line 190, in provide_metadata
    return fn(*args, **kw)
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/SQLAlchemy-0.9.4-py2.7-macosx-10.9-x86_64.egg/sqlalchemy/testing/suite/test_types.py", line 34, in _literal_round_trip
    testing.db.execute(ins)
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/SQLAlchemy-0.9.4-py2.7-macosx-10.9-x86_64.egg/sqlalchemy/engine/base.py", line 1682, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/SQLAlchemy-0.9.4-py2.7-macosx-10.9-x86_64.egg/sqlalchemy/engine/base.py", line 720, in execute
    return meth(self, multiparams, params)
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/SQLAlchemy-0.9.4-py2.7-macosx-10.9-x86_64.egg/sqlalchemy/sql/compiler.py", line 207, in _execute_on_connection
    return connection._execute_compiled(self, multiparams, params)
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/SQLAlchemy-0.9.4-py2.7-macosx-10.9-x86_64.egg/sqlalchemy/engine/base.py", line 839, in _execute_compiled
    compiled, parameters
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/SQLAlchemy-0.9.4-py2.7-macosx-10.9-x86_64.egg/sqlalchemy/engine/base.py", line 947, in _execute_context
    context)
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/SQLAlchemy-0.9.4-py2.7-macosx-10.9-x86_64.egg/sqlalchemy/engine/base.py", line 1111, in _handle_dbapi_exception
    util.reraise(*exc_info)
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/SQLAlchemy-0.9.4-py2.7-macosx-10.9-x86_64.egg/sqlalchemy/engine/base.py", line 940, in _execute_context
    context)
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/SQLAlchemy-0.9.4-py2.7-macosx-10.9-x86_64.egg/sqlalchemy/engine/default.py", line 435, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python2.7/site-packages/monetdb/sql/cursors.py", line 140, in execute
    operation = unicode(operation).encode('utf-8')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 90: ordinal not in range(128)
```

**Comment by gijzelaerr** [comment]
fixed per https://github.com/gijzelaerr/sqlalchemy-monetdb/commit/1685732b3fecf612efb8f449d579b24660cc9428

required a bug fix release also for python-monetdb (11.19.3.2)
