### ISSUE TITLE
5 failing tests in ComponentReflectionTest

### ISSUE THREAD

**Issue by gijzelaerr** [gijzelaerr/sqlalchemy-monetdb#24]
```
test/test_suite.py:23 (ComponentReflectionTest_monetdb+pymonetdb.test_get_foreign_keys)
Traceback (most recent call last):
  File "/Users/gijs/Work/sqlalchemy-monetdb/test/test_suite.py", line 27, in test_get_foreign_keys
    self._test_get_foreign_keys(schema='test_schema2')
  File "<string>", line 2, in _test_get_foreign_keys
  File "/Users/gijs/Work/sqlalchemy-monetdb/.venv2/lib/python2.7/site-packages/sqlalchemy/testing/util.py", line 196, in provide_metadata
    return fn(*args, **kw)
  File "/Users/gijs/Work/sqlalchemy-monetdb/.venv2/lib/python2.7/site-packages/sqlalchemy/testing/suite/test_reflection.py", line 513, in _test_get_foreign_keys
    eq_(fkey1['name'], "user_id_fk")
  File "/Users/gijs/Work/sqlalchemy-monetdb/.venv2/lib/python2.7/site-packages/sqlalchemy/testing/assertions.py", line 222, in eq_
    assert a == b, msg or "%r != %r" % (a, b)
AssertionError: u'users_parent_user_id_fkey' != 'user_id_fk'
FAILED
.venv2/lib/python2.7/site-packages/sqlalchemy/testing/suite/test_reflection.py:537 (ComponentReflectionTest_monetdb+pymonetdb.test_get_foreign_keys_with_schema)
Traceback (most recent call last):
  File "/Users/gijs/Work/sqlalchemy-monetdb/.venv2/lib/python2.7/site-packages/sqlalchemy/testing/suite/test_reflection.py", line 541, in test_get_foreign_keys_with_schema
    self._test_get_foreign_keys(schema=testing.config.test_schema)
  File "<string>", line 2, in _test_get_foreign_keys
  File "/Users/gijs/Work/sqlalchemy-monetdb/.venv2/lib/python2.7/site-packages/sqlalchemy/testing/util.py", line 196, in provide_metadata
    return fn(*args, **kw)
  File "/Users/gijs/Work/sqlalchemy-monetdb/.venv2/lib/python2.7/site-packages/sqlalchemy/testing/suite/test_reflection.py", line 513, in _test_get_foreign_keys
    eq_(fkey1['name'], "user_id_fk")
  File "/Users/gijs/Work/sqlalchemy-monetdb/.venv2/lib/python2.7/site-packages/sqlalchemy/testing/assertions.py", line 222, in eq_
    assert a == b, msg or "%r != %r" % (a, b)
AssertionError: u'users_parent_user_id_fkey' != 'user_id_fk'
PASSEDPASSEDFAILED
.venv2/lib/python2.7/site-packages/sqlalchemy/testing/suite/test_reflection.py:650 (ComponentReflectionTest_monetdb+pymonetdb.test_get_noncol_index_no_pk)
Traceback (most recent call last):
  File "/Users/gijs/Work/sqlalchemy-monetdb/.venv2/lib/python2.7/site-packages/sqlalchemy/testing/suite/test_reflection.py", line 653, in test_get_noncol_index_no_pk
    self._test_get_noncol_index("noncol_idx_test_nopk", "noncol_idx_nopk")
  File "<string>", line 2, in _test_get_noncol_index
  File "/Users/gijs/Work/sqlalchemy-monetdb/.venv2/lib/python2.7/site-packages/sqlalchemy/testing/util.py", line 196, in provide_metadata
    return fn(*args, **kw)
  File "/Users/gijs/Work/sqlalchemy-monetdb/.venv2/lib/python2.7/site-packages/sqlalchemy/testing/suite/test_reflection.py", line 635, in _test_get_noncol_index
    indexes = insp.get_indexes(tname)
  File "/Users/gijs/Work/sqlalchemy-monetdb/.venv2/lib/python2.7/site-packages/sqlalchemy/engine/reflection.py", line 481, in get_indexes
    info_cache=self.info_cache, **kw)
  File "/Users/gijs/Work/sqlalchemy-monetdb/sqlalchemy_monetdb/dialect.py", line 299, in get_indexes
    "table_id": self._table_id(connection, table_name, schema)})
  File "<string>", line 2, in _table_id
  File "/Users/gijs/Work/sqlalchemy-monetdb/.venv2/lib/python2.7/site-packages/sqlalchemy/engine/reflection.py", line 42, in cache
    return fn(self, con, *args, **kw)
  File "/Users/gijs/Work/sqlalchemy-monetdb/sqlalchemy_monetdb/dialect.py", line 158, in _table_id
    raise exc.NoSuchTableError(table_name)
NoSuchTableError: noncol_idx_test_nopk
FAILED
.venv2/lib/python2.7/site-packages/sqlalchemy/testing/suite/test_reflection.py:654 (ComponentReflectionTest_monetdb+pymonetdb.test_get_noncol_index_pk)
Traceback (most recent call last):
  File "/Users/gijs/Work/sqlalchemy-monetdb/.venv2/lib/python2.7/site-packages/sqlalchemy/testing/suite/test_reflection.py", line 657, in test_get_noncol_index_pk
    self._test_get_noncol_index("noncol_idx_test_pk", "noncol_idx_pk")
  File "<string>", line 2, in _test_get_noncol_index
  File "/Users/gijs/Work/sqlalchemy-monetdb/.venv2/lib/python2.7/site-packages/sqlalchemy/testing/util.py", line 196, in provide_metadata
    return fn(*args, **kw)
  File "/Users/gijs/Work/sqlalchemy-monetdb/.venv2/lib/python2.7/site-packages/sqlalchemy/testing/suite/test_reflection.py", line 635, in _test_get_noncol_index
    indexes = insp.get_indexes(tname)
  File "/Users/gijs/Work/sqlalchemy-monetdb/.venv2/lib/python2.7/site-packages/sqlalchemy/engine/reflection.py", line 481, in get_indexes
    info_cache=self.info_cache, **kw)
  File "/Users/gijs/Work/sqlalchemy-monetdb/sqlalchemy_monetdb/dialect.py", line 299, in get_indexes
    "table_id": self._table_id(connection, table_name, schema)})
  File "<string>", line 2, in _table_id
  File "/Users/gijs/Work/sqlalchemy-monetdb/.venv2/lib/python2.7/site-packages/sqlalchemy/engine/reflection.py", line 42, in cache
    return fn(self, con, *args, **kw)
  File "/Users/gijs/Work/sqlalchemy-monetdb/sqlalchemy_monetdb/dialect.py", line 158, in _table_id
    raise exc.NoSuchTableError(table_name)
NoSuchTableError: noncol_idx_test_pk
PASSEDPASSEDPASSEDPASSEDPASSEDPASSEDSKIPPED
Skipped: '_test_get_table_oid' : PG specific feature
SKIPPED
Skipped: '_test_get_table_oid' : PG specific feature
PASSEDPASSEDPASSEDPASSEDPASSEDSKIPPED
Skipped: 'test_get_temp_view_columns' : marked as skip
SKIPPED
Skipped: 'test_get_temp_view_names' : marked as skip
FAILED
.venv2/lib/python2.7/site-packages/sqlalchemy/testing/suite/test_reflection.py:658 (ComponentReflectionTest_monetdb+pymonetdb.test_get_unique_constraints)
Traceback (most recent call last):
  File "/Users/gijs/Work/sqlalchemy-monetdb/.venv2/lib/python2.7/site-packages/sqlalchemy/testing/suite/test_reflection.py", line 661, in test_get_unique_constraints
    self._test_get_unique_constraints()
  File "<string>", line 2, in _test_get_unique_constraints
  File "/Users/gijs/Work/sqlalchemy-monetdb/.venv2/lib/python2.7/site-packages/sqlalchemy/testing/util.py", line 196, in provide_metadata
    return fn(*args, **kw)
  File "/Users/gijs/Work/sqlalchemy-monetdb/.venv2/lib/python2.7/site-packages/sqlalchemy/testing/suite/test_reflection.py", line 759, in _test_get_unique_constraints
    assert not idx_names.intersection(uq_names)
AssertionError
FAILED
.venv2/lib/python2.7/site-packages/sqlalchemy/testing/suite/test_reflection.py:686 (ComponentReflectionTest_monetdb+pymonetdb.test_get_unique_constraints_with_schema)
Traceback (most recent call last):
  File "/Users/gijs/Work/sqlalchemy-monetdb/.venv2/lib/python2.7/site-packages/sqlalchemy/testing/suite/test_reflection.py", line 690, in test_get_unique_constraints_with_schema
    self._test_get_unique_constraints(schema=testing.config.test_schema)
  File "<string>", line 2, in _test_get_unique_constraints
  File "/Users/gijs/Work/sqlalchemy-monetdb/.venv2/lib/python2.7/site-packages/sqlalchemy/testing/util.py", line 196, in provide_metadata
    return fn(*args, **kw)
  File "/Users/gijs/Work/sqlalchemy-monetdb/.venv2/lib/python2.7/site-packages/sqlalchemy/testing/suite/test_reflection.py", line 759, in _test_get_unique_constraints
    assert not idx_names.intersection(uq_names)
AssertionError

**Comment by gijzelaerr** [comment]
only one left! disabled the test for now.
